### ISSUE TITLE
timesync problem

### ISSUE THREAD

**Issue by js-fwr** [waterlinked/examples#10]
Hi, i used your examples and the provided [api](https://demo.waterlinked.com/swagger/#/) to create a ros2 node for the uGPS g2. 
Feeding external gps seems to work fine, but apperently im not able to connect a Locator (U1) due to the fact that the system is not able to timesync? (This is what the status report tells me at least). Im not sure if i got anything wrong, but there is no explicit way of setting a external time-source to the topside unit. 
Any suggestions ?

**Comment by wlkh** [comment]
Please contact us on our support channel, and we'll help you out there: https://waterlinked.com/support
